'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/utils/supabase/client'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Lock, CheckCircle, ArrowRight, Trophy } from 'lucide-react'
import Link from 'next/link'
import { useLocale } from '@/contexts/LocaleContext'

// Same themes as in create page, but we should probably centralize this config.
// For now, I'll copy the list to ensure the UI works.
const THEMES_LIST = [
    { id: 'astronaut', emoji: '🚀' },
    { id: 'doctor', emoji: '👨‍⚕️' },
    { id: 'scientist', emoji: '🔬' },
    { id: 'kpop_star', emoji: '🎤' },
    { id: 'chef', emoji: '👨‍🍳' },
    { id: 'pilot', emoji: '✈️' },
    { id: 'athlete', emoji: '⚽' },
    { id: 'artist', emoji: '🎨' },
    { id: 'firefighter', emoji: '🚒' },
    { id: 'police', emoji: '👮' },
    { id: 'teacher', emoji: '📚' },
    { id: 'veterinarian', emoji: '🐾' },
]

export default function CollectionPage() {
    const { t } = useLocale()
    const [collectedThemes, setCollectedThemes] = useState<string[]>([])
    const [loading, setLoading] = useState(true)
    const supabase = createClient()

    useEffect(() => {
        const fetchCollection = async () => {
            const { data: { user } } = await supabase.auth.getUser()

            if (user) {
                // Fetch all distinct themes generated by the user
                const { data } = await supabase
                    .from('generated_images')
                    .select('theme')
                    .eq('user_id', user.id)

                if (data) {
                    const themes = Array.from(new Set(data.map(item => item.theme)))
                    setCollectedThemes(themes as string[])
                }
            } else {
                // Guest mode: check local storage history maybe?
                // For now, collections are a "Logged In" feature to encourage signups.
            }
            setLoading(false)
        }

        fetchCollection()
    }, [])

    const progress = Math.round((collectedThemes.length / THEMES_LIST.length) * 100)

    return (
        <div className="container mx-auto px-4 py-12 max-w-5xl">
            {/* Header */}
            <div className="text-center mb-12">
                <div className="inline-flex items-center gap-2 px-4 py-2 bg-amber-100 text-amber-800 rounded-full text-sm font-medium mb-4">
                    <Trophy className="w-4 h-4" />
                    {t.collection?.badge || 'Career Passport'}
                </div>
                <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                    {t.collection?.title || 'My Career Collection'}
                </h1>
                <p className="text-gray-500 max-w-2xl mx-auto">
                    {t.collection?.description || 'Collect all career cards to unlock a special reward!'}
                </p>
            </div>

            {/* Progress Bar */}
            <div className="mb-12 max-w-xl mx-auto">
                <div className="flex justify-between text-sm mb-2 font-medium">
                    <span>{collectedThemes.length} / {THEMES_LIST.length} {t.collection?.collected || 'Collected'}</span>
                    <span className="text-amber-600">{progress}%</span>
                </div>
                <div className="h-4 bg-gray-100 rounded-full overflow-hidden">
                    <div
                        className="h-full bg-gradient-to-r from-amber-400 to-orange-500 transition-all duration-1000 ease-out"
                        style={{ width: `${progress}%` }}
                    />
                </div>
            </div>

            {/* Sticker Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-6">
                {THEMES_LIST.map((theme) => {
                    const isCollected = collectedThemes.includes(theme.id)
                    const themeName = t.themes[theme.id as keyof typeof t.themes] || theme.id

                    return (
                        <div key={theme.id} className="group relative">
                            <Card className={`aspect-[3/4] p-4 flex flex-col items-center justify-center transition-all ${isCollected
                                    ? 'bg-white border-amber-200 shadow-md transform hover:-translate-y-1'
                                    : 'bg-slate-50 border-slate-200 opacity-75 hover:opacity-100'
                                }`}>
                                <div className={`text-6xl mb-4 transition-transform ${isCollected ? 'scale-110' : 'grayscale opacity-50 group-hover:scale-110 group-hover:grayscale-0'}`}>
                                    {theme.emoji}
                                </div>
                                <h3 className={`font-bold mb-2 ${isCollected ? 'text-slate-900' : 'text-slate-400'}`}>
                                    {themeName}
                                </h3>

                                {isCollected ? (
                                    <div className="mt-2 flex items-center gap-1 text-green-600 text-sm font-medium bg-green-50 px-3 py-1 rounded-full">
                                        <CheckCircle className="w-3 h-3" />
                                        {t.common?.collected || 'Collected'}
                                    </div>
                                ) : (
                                    <Link href={`/create?theme=${theme.id}`} className="mt-2">
                                        <Button size="sm" variant="outline" className="gap-1 border-dashed group-hover:border-solid group-hover:border-amber-500 group-hover:text-amber-600">
                                            <Lock className="w-3 h-3" />
                                            {t.common?.unlock || 'Unlock'}
                                        </Button>
                                    </Link>
                                )}
                            </Card>
                        </div>
                    )
                })}
            </div>

            {/* Guest CTA */}
            {collectedThemes.length === 0 && !loading && (
                <div className="text-center mt-16 p-8 bg-slate-50 rounded-2xl border border-dashed border-slate-300">
                    <p className="text-gray-500 mb-4">
                        {t.collection?.emptyState || 'Start creating portraits to fill your collection!'}
                    </p>
                    <Link href="/create">
                        <Button className="bg-amber-600 hover:bg-amber-700">
                            {t.hero?.cta || 'Start Creating'} <ArrowRight className="ml-2 w-4 h-4" />
                        </Button>
                    </Link>
                </div>
            )}
        </div>
    )
}
