'use client'

import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Sparkles } from 'lucide-react'
import TrustBanner from './TrustBanner'

export default function HeroSection({ locale }: { locale: string }) {
    return (
        <section className="relative w-full min-h-[90vh] flex items-center bg-[#F8F9FA] overflow-hidden">
            <div className="container mx-auto px-4 h-full">
                <div className="flex flex-col lg:flex-row h-full items-center gap-12 lg:gap-20">

                    {/* Left Column: Hero Image (Visual First) */}
                    <div className="w-full lg:w-1/2 relative h-[500px] lg:h-[800px] rounded-3xl overflow-hidden shadow-2xl order-1 lg:order-1 mt-8 lg:mt-0">
                        {/* Placeholder for high-quality example - Replace with actual generated results later */}
                        <div className="absolute inset-0 bg-gray-200 animate-pulse" />

                        {/* Dramatic Lighting Effect Overlay */}
                        <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent z-10" />

                        {/* Example Images Carousel or Single Hero Image */}
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                            src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1888&auto=format&fit=crop"
                            alt="AI Portrait Example"
                            className="absolute inset-0 w-full h-full object-cover z-0 hover:scale-105 transition-transform duration-700"
                        />

                        <div className="absolute bottom-8 left-8 z-20 text-white/90 font-medium tracking-wide">
                            {locale === 'ko' ? 'Generated by DearMyKids AI' : 'Generated by DearMyKids AI'}
                        </div>
                    </div>

                    {/* Right Column: Text & CTA */}
                    <div className="w-full lg:w-1/2 flex flex-col justify-center items-start text-left order-2 lg:order-2 pb-12 lg:pb-0">
                        <div className="mb-6">
                            <TrustBanner locale={locale} />
                        </div>

                        <h2 className="text-sm font-bold tracking-widest text-blue-600 mb-4 uppercase">
                            {locale === 'ko' ? 'AI 기반 진로 탐색 도구' : 'AI-POWERED CAREER EXPLORATION'}
                        </h2>

                        <h1 className="text-5xl lg:text-7xl font-black tracking-tight text-slate-900 mb-6 leading-[1.1]">
                            {locale === 'ko' ? (
                                <>
                                    나만의 AI 퍼스널 <br />
                                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600 italic pr-2">
                                        스타일리스트
                                    </span>
                                </>
                            ) : (
                                <>
                                    Your Personal AI <br />
                                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600 italic pr-2">
                                        Stylist
                                    </span>
                                </>
                            )}
                        </h1>

                        <p className="text-xl text-gray-500 mb-10 max-w-lg leading-relaxed font-light">
                            {locale === 'ko'
                                ? '사진과 신체 정보를 기반으로 AI가 맞춤형 패션 추천과 헤어스타일을 제안합니다. 우리 아이의 미래 모습을 지금 바로 확인해보세요.'
                                : 'AI suggests personalized fashion and hairstyles based on photos and body information. Discover your child\'s future look right now.'
                            }
                        </p>

                        <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
                            <Link href="/create" className="w-full sm:w-auto">
                                <Button size="lg" className="w-full sm:w-auto h-16 px-10 text-xl font-bold bg-blue-600 hover:bg-blue-700 text-white rounded-full shadow-lg hover:shadow-blue-500/30 transition-all">
                                    {locale === 'ko' ? '시작하기' : 'Start Creating'}
                                </Button>
                            </Link>
                        </div>

                        <p className="text-xs text-gray-400 mt-4 ml-2">
                            {locale === 'ko' ? '회원가입 불필요. 즉시 AI 분석.' : 'No sign-up required. Instant analysis.'}
                        </p>
                    </div>

                </div>
            </div>
        </section>
    )
}
